version: "3.6"
services:
    postgres:
        container_name: postgres_gophermart
        image: postgres:15-alpine
        restart: always
        environment:
            POSTGRES_USER: "root"
            POSTGRES_PASSWORD: "12345"
            POSTGRES_DB: "gophermart"
            #PGDATA: /tmp
#        volumes:
#            - ./database:/var/lib/postgresql/data
        ports:
            - "5432:5432"